version: '3.7'

services:
  app:
    build: .
    image: got:latest
    command: nodemon app.js
    volumes:
      - .:/usr/scr/app
    ports: 
      - "8080:8080"
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports: 
      - "27017:27017"
    volumes:
    - data-volume:/data/db

volumes:
  data-volume:
      